<p>
    <a href ="<?php echo $this->url(
                array(
                    'controller'=>'variables', //replace _ with -
                    'action'    =>'add'
                    ),
                    'default',
                    true) ?>">Add Variables Name</a>
    </p>
    Variables Entries: <br />
    <dl>
        <?php foreach ($this->entries as $entry):?>
        
            <dt><?php echo $this->escape($entry->Id)?></dt>
            <dt><?php echo $this->escape($entry->Name)?></dt>
            <dt><?php echo $this->escape($entry->Value)?></dt>
            <dt><?php echo $this->escape($entry->Description)?></dt>
       <br/>
        <?php endforeach ?>
    </dl>
        