<p>
    <a href ="<?php echo $this->url(
                array(
                    'controller'=>'user', //replace _ with -
                    'action'    =>'add'
                    ),
                    'default',
                    true) ?>">Add User Name</a>
    </p>
    User Entries: <br />
    <dl>
        <?php foreach ($this->entries as $entry):?>
        
            <dt><?php echo $this->escape($entry->Id)?></dt>
            <dt><?php echo $this->escape($entry->Token)?></dt>
            <dt><?php echo $this->escape($entry->Username)?></dt>
            <dt><?php echo $this->escape($entry->Email)?></dt>
            <dt><?php echo $this->escape($entry->RoleId)?></dt>
            <dt><?php echo $this->escape($entry->IsActive)?></dt>
            <dt><?php echo $this->escape($entry->Credibility)?></dt>
       <br/>
        <?php endforeach ?>
    </dl>
        