<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
	  <title>ATM Locator</title>
	  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<?php
    /*
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/style.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/960.css');
    echo $this->headLink();
	 
	$this->headScript()->prependFile($this->baseUrl() . '/js/jquery-1.3.2.min.js', $type = 'text/javascript');
    print $this->headScript();
     */
	?>
  </head>
	<body>
		<div class="container_12">
      <div id="wrapper" class="grid_12">
  			<div class="grid_3 alpha rightbar">

                <div id="header" class="grid_3 alpha omega logo">
                    <!--<img alt="logo" src="<?php //print $this->baseUrl()?>/images/logo.png">-->
                    <h1 class="title">ATM Locator</h1>
                </div>
			
			<div id="navigation" class="grid_3 alpha omega menu">
				<ul class="menu-list">
					<li>Links will appear here</li>
			  </ul>
			</div>
		  </div>
	    <div class="grid_9 omega">
		    <div class="content">
			  <?php print $this->layout()->content;?>
  			</div>
	    </div>
    </div>
  	<div id="footer-wrapper" class="grid_12">
		  <div id="footer">
		  <!--
		    HackJatra 2010
		  -->
	    </div>
	</div>
</div>

</body>

</html>

